import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const initialProjects = [
  { id: 1, name: 'Website redesign', status: 'In review', tasks: 12, done: 9, owner: 'Maya', due: 'Sep 18' },
  { id: 2, name: 'Mobile onboarding', status: 'On track', tasks: 8, done: 5, owner: 'Andre', due: 'Sep 23' },
  { id: 3, name: 'Q3 research', status: 'At risk', tasks: 4, done: 1, owner: 'Robin', due: 'Sep 15' },
];
const initialTasks = [
  { id: 1, title: 'Review homepage prototype', project: 'Website redesign', complete: false, due: 'Today' },
  { id: 2, title: 'Confirm welcome email copy', project: 'Mobile onboarding', complete: false, due: 'Tomorrow' },
  { id: 3, title: 'Share interview themes', project: 'Q3 research', complete: true, due: 'Yesterday' },
];
const people = [['Maya Chen', 'Design lead', 'MC', '#d98f5c'], ['Andre Brooks', 'Product manager', 'AB', '#648bb3'], ['Robin Nguyen', 'Research', 'RN', '#456b59'], ['Nina Shah', 'Engineering', 'NS', '#9b7764']];

function App() {
  const [view, setView] = useState('Overview');
  const [projects, setProjects] = useState(initialProjects);
  const [tasks, setTasks] = useState(initialTasks);
  const [taskText, setTaskText] = useState('');
  const [selectedProject, setSelectedProject] = useState(null);
  const [showInvite, setShowInvite] = useState(false);
  const [showSearch, setShowSearch] = useState(false);
  const [showProfile, setShowProfile] = useState(false);
  const [search, setSearch] = useState('');
  const [notice, setNotice] = useState('');
  const [activity, setActivity] = useState(['Maya moved Website redesign to review', 'Andre completed a mobile onboarding task', 'Nina joined the workspace']);
  const openTasks = tasks.filter((task) => !task.complete);
  const filteredProjects = useMemo(() => projects.filter((project) => project.name.toLowerCase().includes(search.toLowerCase())), [projects, search]);
  const announce = (message) => setNotice(message);
  const changeView = (next) => { setView(next); setSelectedProject(null); setShowProfile(false); };
  const openProject = (project) => { setSelectedProject(project); setView('Project'); };
  function addTask(event) { event.preventDefault(); const title = taskText.trim(); if (!title) return announce('Write a task before adding it'); const task = { id: Date.now(), title, project: selectedProject?.name ?? 'General', complete: false, due: 'No date' }; setTasks((current) => [task, ...current]); setTaskText(''); setActivity((current) => [`You added “${title}”`, ...current]); announce(`Added “${title}”`); }
  function toggleTask(id) { const task = tasks.find((item) => item.id === id); setTasks((current) => current.map((item) => item.id === id ? { ...item, complete: !item.complete } : item)); announce(task.complete ? `Reopened “${task.title}”` : `Completed “${task.title}”`); }
  function updateProjectStatus(status) { setProjects((current) => current.map((project) => project.id === selectedProject.id ? { ...project, status } : project)); setSelectedProject((project) => ({ ...project, status })); announce(`Project marked ${status.toLowerCase()}`); }
  function sendInvite(event) { event.preventDefault(); setShowInvite(false); setActivity((current) => ['You invited a new teammate', ...current]); announce('Invite sent to your teammate'); }
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">N</span> Northstar</div><nav>{['Overview', 'Projects', 'People', 'Reports'].map((item) => <div className={`nav-item ${view === item ? 'active' : ''}`} key={item} onClick={() => changeView(item)}>{item === 'Overview' ? '⌂' : item === 'Projects' ? '▦' : item === 'People' ? '♙' : '◴'} {item}</div>)}</nav><div className="sidebar-footer">Need a hand? <a href="#help">Visit help</a></div></aside>
    <main><header className="topbar"><div><p className="kicker">Friday, September 12</p><h1>{view === 'Overview' ? 'Good morning, Robin' : view === 'Project' ? selectedProject.name : view}</h1></div><div className="top-actions"><button className="icon-button" onClick={() => setShowSearch(true)}>⌕</button><button className="avatar" onClick={() => setShowProfile((open) => !open)}>RN</button>{showProfile && <div className="profile-menu"><strong>Robin Nguyen</strong><span>robin@northstar.co</span><button onClick={() => announce('Preferences saved')}>Preferences</button><button onClick={() => announce('Signed out')}>Sign out</button></div>}</div></header>
    {notice && <div className="notice">{notice}<button onClick={() => setNotice('')}>×</button></div>}
    {view === 'Overview' && <Overview projects={projects} tasks={tasks} openTasks={openTasks} activity={activity} onProject={openProject} onInvite={() => setShowInvite(true)} onToggle={toggleTask} onAdd={addTask} taskText={taskText} setTaskText={setTaskText} />}
    {view === 'Projects' && <Projects projects={projects} onProject={openProject} onCreate={() => { const project = { id: Date.now(), name: 'Untitled project', status: 'On track', tasks: 0, done: 0, owner: 'Robin', due: 'No date' }; setProjects((current) => [...current, project]); openProject(project); }} />}
    {view === 'Project' && <ProjectDetail project={selectedProject} tasks={tasks.filter((task) => task.project === selectedProject.name)} onBack={() => changeView('Projects')} onStatus={updateProjectStatus} onToggle={toggleTask} />}
    {view === 'People' && <People onInvite={() => setShowInvite(true)} />}{view === 'Reports' && <Reports projects={projects} tasks={tasks} />}</main>
    {showSearch && <div className="modal-backdrop"><div className="modal search-modal" role="dialog"><button className="modal-close" onClick={() => setShowSearch(false)}>×</button><h2>Find a project</h2><input autoFocus placeholder="Start typing a project name" value={search} onChange={(event) => setSearch(event.target.value)} />{filteredProjects.map((project) => <div className="search-result" key={project.id} onClick={() => { openProject(project); setShowSearch(false); setSearch(''); }}>✦ {project.name}<small>{project.status}</small></div>)}</div></div>}
    {showInvite && <div className="modal-backdrop"><form className="modal" role="dialog" onSubmit={sendInvite}><button type="button" className="modal-close" onClick={() => setShowInvite(false)}>×</button><h2>Bring someone in</h2><p>They’ll get an email with access to this workspace.</p><input type="email" placeholder="name@company.com" required /><select defaultValue="Member"><option>Member</option><option>Admin</option><option>Viewer</option></select><button className="primary">Send invite</button></form></div>}
  </div>;
}

function Overview({ projects, tasks, openTasks, activity, onProject, onInvite, onToggle, onAdd, taskText, setTaskText }) { return <>
  <section className="hero" aria-describedby="missing-description"><div><h3>Make the next release count.</h3><p>Keep every important project and conversation in one calm place.</p><button className="primary" onClick={onInvite}>Invite teammate</button></div><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=700&q=80" /></section>
  <section className="overview-grid"><div className="metric-card"><p>Open tasks</p><strong>{openTasks.length + 25}</strong><span>↑ 12% this week</span></div><div className="metric-card"><p>Team focus</p><strong>84%</strong><span>Good momentum</span></div><div className="metric-card"><p>Due today</p><strong>{tasks.filter((task) => task.due === 'Today').length + 4}</strong><span className="warning">Needs attention</span></div></section>
  <section className="projects"><SectionHeading title="Active projects" action="See all projects" /><div className="project-list">{projects.slice(0, 3).map((project) => <ProjectRow key={project.id} project={project} onClick={() => onProject(project)} />)}</div></section>
  <section className="split-section"><div className="quick-add"><h2>Capture a thought</h2><form className="capture-line" onSubmit={onAdd}><input value={taskText} onChange={(event) => setTaskText(event.target.value)} placeholder="What needs doing?" /><button className="add">Add task</button></form><p className="muted">Press <kbd>⌘</kbd> + <kbd>Enter</kbd> to add quickly</p><TaskList tasks={tasks.slice(0, 3)} onToggle={onToggle} /></div><div className="activity"><h2>Team activity</h2>{activity.slice(0, 4).map((item, index) => <div className="activity-item" key={`${item}-${index}`}><span className="activity-dot" />{item}<small>{index + 1}h ago</small></div>)}</div></section></>; }
function Projects({ projects, onProject, onCreate }) { return <section className="view-section"><div className="view-intro"><div><h2>Every project, in one view</h2><p>See ownership, progress, and the next thing that matters.</p></div><button className="primary" onClick={onCreate}>New project</button></div><div className="project-board">{projects.map((project) => <div className="project-card" key={project.id} onClick={() => onProject(project)}><div className="card-top"><span className="project-icon">✦</span><span className={`status ${project.status.replace(' ', '-').toLowerCase()}`}>{project.status}</span></div><h3>{project.name}</h3><p>{project.owner} · due {project.due}</p><div className="progress-track"><span style={{ width: `${project.tasks ? (project.done / project.tasks) * 100 : 0}%` }} /></div><small>{project.done} of {project.tasks} tasks complete</small></div>)}</div></section>; }
function ProjectDetail({ project, tasks, onBack, onStatus, onToggle }) { return <section className="view-section"><button className="back-link" onClick={onBack}>← All projects</button><div className="detail-heading"><div><span className={`status ${project.status.replace(' ', '-').toLowerCase()}`}>{project.status}</span><h2>{project.name}</h2><p>Owned by {project.owner} · due {project.due}</p></div><select value={project.status} onChange={(event) => onStatus(event.target.value)}><option>On track</option><option>In review</option><option>At risk</option></select></div><div className="detail-grid"><div className="task-panel"><h2>Project tasks</h2><TaskList tasks={tasks} onToggle={onToggle} empty="No tasks yet. Capture one from the dashboard." /></div><div className="project-notes"><h3>Project notes</h3><textarea placeholder="Add a note for your team…" /><button className="primary">Save note</button><img src="https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=500&q=80" /></div></div></section>; }
function People({ onInvite }) { return <section className="view-section"><div className="view-intro"><div><h2>People make the work move</h2><p>Four teammates are active in Northstar this week.</p></div><button className="primary" onClick={onInvite}>Invite teammate</button></div><div className="people-grid">{people.map(([name, role, initials, color]) => <div className="person-card" key={name}><span className="person-avatar" style={{ background: color }}>{initials}</span><strong>{name}</strong><p>{role}</p><button onClick={() => alert(`Message composer opened for ${name}`)}>Message</button></div>)}</div></section>; }
function Reports({ projects, tasks }) { const completed = tasks.filter((task) => task.complete).length; return <section className="view-section"><div className="view-intro"><div><h2>Work is moving forward</h2><p>A compact weekly read on where the team spent its energy.</p></div><button className="ghost-button" onClick={() => window.print()}>Print report</button></div><div className="report-number"><strong>{Math.round((completed / tasks.length) * 100) || 0}%</strong><span>of tracked tasks completed</span></div><div className="bar-chart">{projects.map((project) => <div key={project.id}><span style={{ height: `${Math.max(22, (project.done / Math.max(project.tasks, 1)) * 160)}px` }} /><small>{project.name.split(' ')[0]}</small></div>)}</div><div className="report-callout"><h3>One thing to watch</h3><p>Q3 research has one completed task and is due in three days. A short decision session will help it regain momentum.</p></div></section>; }
function SectionHeading({ title, action }) { return <div className="section-heading"><div><h2>{title}</h2><p>Your team’s work, at a glance.</p></div><a href="#projects">{action} →</a></div>; }
function ProjectRow({ project, onClick }) { return <div className="project-row" onClick={onClick}><div className="project-icon">✦</div><div className="project-name"><strong>{project.name}</strong><small>{project.tasks} tasks</small></div><span className={`status ${project.status.replace(' ', '-').toLowerCase()}`}>{project.status}</span><span className="chevron">›</span></div>; }
function TaskList({ tasks, onToggle, empty }) { if (!tasks.length) return <p className="empty-state">{empty}</p>; return <div className="task-list">{tasks.map((task) => <div className={`task-item ${task.complete ? 'complete' : ''}`} key={task.id}><button className="check" onClick={() => onToggle(task.id)}>{task.complete ? '✓' : ''}</button><span>{task.title}<small>{task.project} · {task.due}</small></span></div>)}</div>; }
createRoot(document.getElementById('root')).render(<App />);
